# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.2.3
  qodana: jetbrains/qodana@2023.2

# Define a job to be invoked later in a workflow.
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn coverage
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - codecov/upload:
          file: coverage/clover.xml
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      - qodana/scan

# Invoke jobs via workflows
workflows:
  build_and_test-workflow:
    jobs:
      - build_and_test
      - code-quality:
          context: qodana
          requires:
            - build_and_test
