# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.2.3

# Define a job to be invoked later in a workflow.
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - codecov/upload
        parameters:
          file: coverage/clover.xml

# Invoke jobs via workflows
workflows:
  build_and_test-workflow:
    jobs:
      - build_and_test
